version: "3.7"

services:
        spark-master:
                build:
                        context: ./base
                        target: spark-master
                ports:
                        - "8080:8080"
                        - "7077:7077"
                networks:
                        - spark-network
                volumes:
                        - spark-vol:/data
        spark-worker:
                build:
                        context: ./base
                        target: spark-worker
                command: ["--webui-port", "8080", "spark://spark-master:7077"]
                networks:
                        - spark-network
                volumes:
                        - spark-vol:/data

        #pyspark-shell:
                #depends_on:
                        #- spark-master
                        #- spark-worker
                #build:
                        #context: ./base
                        #target: pyspark-shell
                #tty: true
                #command: ["--master", "spark://spark-master:7077"]
                #networks:
                        #- spark-network
                #volumes:
                        #- spark-vol:/data
        pyspark-notebook:
                depends_on:
                        - spark-master
                        - spark-worker
                build:
                        context: ./base
                        target: pyspark-notebook
                command: ["--master", "spark://spark-master:7077"]
                init: true
                ports:
                        - "8888:8888"
                networks:
                        - spark-network
                volumes:
                        - spark-vol:/data

        # Uncomment to spin-up the example application
        #spark-example:
                #depends_on:
                        #- spark-master
                        #- spark-worker
                #build:
                        #context: ./base
                        #target: spark-submit
                #networks:
                        #- spark-network

networks:
        spark-network:
                driver: bridge

volumes:
        spark-vol:
